In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
training_df= pd.read_csv('customer_churn_dataset-training-master.csv')
training_df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [4]:
testing_df= pd.read_csv('customer_churn_dataset-testing-master.csv')
testing_df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [6]:
df= pd.merge(training_df, testing_df, on= 'CustomerID')
df

,CustomerID,Age_x,Gender_x,Tenure_x,Usage Frequency_x,Support Calls_x,Payment Delay_x,Subscription Type_x,Contract Length_x,Total Spend_x,...,Gender_y,Tenure_y,Usage Frequency_y,Support Calls_y,Payment Delay_y,Subscription Type_y,Contract Length_y,Total Spend_y,Last Interaction_y,Churn_y
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,...,Female,28,28,7,13,Standard,Monthly,584,20,0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,...,Male,27,10,2,29,Premium,Annual,757,21,0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,...,Male,9,12,5,17,Premium,Quarterly,232,18,0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,...,Female,58,24,9,2,Standard,Annual,533,18,0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,...,Male,41,14,10,10,Premium,Monthly,500,29,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62990,64369.0,58.0,Female,10.0,12.0,0.0,22.0,Premium,Monthly,822.0,...,Male,3,1,5,11,Standard,Annual,218,15,1
62991,64370.0,36.0,Male,15.0,16.0,6.0,11.0,Standard,Monthly,284.0,...,Female,33,12,6,21,Basic,Quarterly,947,14,1
62992,64372.0,38.0,Female,36.0,25.0,0.0,17.0,Premium,Quarterly,868.0,...,Male,39,14,8,30,Premium,Monthly,327,20,1
62993,64373.0,40.0,Female,34.0,29.0,1.0,27.0,Premium,Annual,790.0,...,Female,18,19,7,22,Standard,Monthly,540,13,1
62994,64374.0,19.0,Male,5.0,16.0,5.0,1.0,Premium,Quarterly,874.0,...,Female,45,15,9,25,Standard,Monthly,696,22,1