In [61]:
import pandas as pd

In [62]:
movie= pd.read_csv('tmdb_5000_movies.csv')
credits= pd.read_csv('tmdb_5000_credits.csv')
movie.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [63]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [64]:
movies= movie.merge(credits, on='title')
movies.shape

(4809, 23)

In [65]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   str
 2   homepage              1713 non-null   str
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   str
 5   original_language     4809 non-null   str
 6   original_title        4809 non-null   str
 7   overview              4806 non-null   str
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   str
 10  production_countries  4809 non-null   str
 11  release_date          4808 non-null   str
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   str
 15  status                4809 non-null   str
 16  tagline               3965 non-null   str
 17  title                 4809 non-null   str
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   str
 22  crew                  4809 non-null   str
dtypes: float64(3), int64(5), str(15)
memory usage: 864.2 KB

In [66]:
movies= movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [67]:
movies.isnull().sum().sort_values(ascending=False)

overview    3
movie_id    0
title       0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [68]:
movies.dropna(inplace=True)

In [69]:
movies.isnull().sum().sort_values(ascending=False)

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [70]:
movies.duplicated().sum()

np.int64(0)

In [71]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

### Change the format
'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
["Action", "Adventure", "Fantasy", "Science Fiction"]

In [72]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [73]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L   # ✅ Outside the loop, after collecting all names

In [74]:
movies['genres']=movies['genres'].apply(convert)

In [75]:
def convert(object):
    l=[]
    counter=0
    for i in ast.literal_eval(object):
        if counter!=3:
            l.append(i['name'])
            counter=+1
        else:
            break
    return l

In [76]:
movies['keywords']=movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [77]:
movies['cast']= movies['cast'].apply(convert)

In [78]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [79]:
def fetch_Director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job']== 'Director':
            L.append(i['name'])
            break
    return L   # ✅ Outside the loop, after collecting all names

In [80]:
movies['crew']= movies['crew'].apply(fetch_Director)

In [81]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [82]:
movies['overview']= movies['overview'].apply(lambda x: x.split())

In [83]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [84]:
movies['genres']= movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['keywords']= movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['cast']= movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['crew']= movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x])
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [85]:
movies['tags']= movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [86]:
df= movies[['movie_id', 'title', 'tags']]
df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [87]:
df['tags']= df['tags'].apply(lambda x: " ".join(x))
df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [88]:
df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee JamesCameron'

In [89]:
df['tags']= df['tags'].apply(lambda x: x.lower())

In [90]:

df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [91]:
df['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenb.madden josephbradymadden frankietorres austinwilson sarawilson tamicawashington-miller lucybriant nathanmeister gerryblair matthewchamberlain paulyates wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrell brandonjelkes micahmoch hanniyahmuhammad christophernolen christaoliver aprilmariethomas bravitaa.threatt colinbleasdale mikebodnar mattclayton nicoledionne jamieharrison allanhenry anthonyingruber ashleyjeffery deanknowsley josephmika-hunt terrynotary kaipantano loganpithyou stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhiteside nikiezambo julenerenee jamescameron'

In [92]:
df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley stellanskarsgård chowyun-fat billnighy geoffreyrush jackdavenport kevinmcnally tomhollander naomieharris jonathanpryce keithrichards leearenberg mackenziecrook gregellis davidbailie martinklebba davidschofield laurenmaher vanessabranch angusbarnett gilesnew reggielee dominicscottkay takayofischer davidmeunier ho-kwantse andybeckwith peterdonaldbadalamentiii christophers.capp keithrichards hakeemkae-kazim ghassanmassoud goreverbinski"

In [93]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000, stop_words='english')

In [94]:
vectors= cv.fit_transform(df['tags']).toarray().shape
vectors

(4806, 5000)

In [95]:
vectors[0]

4806

In [96]:
len(cv.get_feature_names_out())

5000

In [97]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zoo', 'zooeydeschanel', 'zoëkravitz'],
      shape=(5000,), dtype=object)

In [98]:
import nltk
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [99]:
def stem(text):
    y=[]

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [104]:
df['tags']= df['tags'].apply(stem)

In [105]:
df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene jamescameron'

In [106]:
stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenb.madden josephbradymadden frankietorres austinwilson sarawilson tamicawashington-miller lucybriant nathanmeister gerryblair matthewchamberlain paulyates wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrell brandonjelkes micahmoch hanniyahmuhammad christophernolen christaoliver aprilmariethomas bravitaa.threatt colinbleasdale mikebodnar mattclayton nicoledionne jamieharrison allanhenry anthonyingruber ashleyjeffery deanknowsley josephmika-hunt terrynotary kaipantano loganpithyou stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhiteside nikiezambo julenerenee jamescameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene jamescameron'

In [107]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000, stop_words='english')

In [108]:
vectors= cv.fit_transform(df['tags']).toarray()

c:\Users\Summaiya\AppData\Local\miniconda3\envs\myenv\Lib\site-packages\jedi\inference\compiled\subprocess\functions.py:21: UserWarning: Module numpy._core.array not importable in path ['c:\\Users\\Summaiya\\AppData\\Local\\miniconda3\\envs\\myenv\\python311.zip', 'c:\\Users\\Summaiya\\AppData\\Local\\miniconda3\\envs\\myenv\\DLLs', 'c:\\Users\\Summaiya\\AppData\\Local\\miniconda3\\envs\\myenv\\Lib', 'c:\\Users\\Summaiya\\AppData\\Local\\miniconda3\\envs\\myenv', 'c:\\Users\\Summaiya\\AppData\\Local\\miniconda3\\envs\\myenv\\Lib\\site-packages'].
  return access.load_module(inference_state, **kwargs)

In [109]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [110]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [111]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zoo', 'zooeydeschanel', 'zoëkravitz'],
      shape=(5000,), dtype=object)

In [103]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))   # ✅ append() method, phir stem(i)
    return " ".join(y)

df['tags'].apply(stem)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: str

In [112]:
ps.stem('danced')

'danc'

In [53]:
print(type(df['tags'][0]))   # list ya str?

<class 'str'>

In [54]:
text = "in the 22nd century, a paraplegic marine is dispatched to the moon pandora ..."
stemmed = stem(text)
print(stemmed)

in the 22nd century, a parapleg marin is dispatch to the moon pandora ...

In [113]:
from sklearn.metrics.pairwise import cosine_similarity

In [59]:
print(type(vectors))
print(vectors)

<class 'tuple'>
(4806, 5000)

In [114]:
cosine_similarity(vectors)

array([[1.        , 0.06745406, 0.07733089, ..., 0.04313311, 0.        ,
        0.        ],
       [0.06745406, 1.        , 0.07476672, ..., 0.02085144, 0.        ,
        0.02331262],
       [0.07733089, 0.07476672, 1.        , ..., 0.02390457, 0.        ,
        0.        ],
       ...,
       [0.04313311, 0.02085144, 0.02390457, ..., 1.        , 0.04264014,
        0.04472136],
       [0.        , 0.        , 0.        , ..., 0.04264014, 1.        ,
        0.09534626],
       [0.        , 0.02331262, 0.        , ..., 0.04472136, 0.09534626,
        1.        ]], shape=(4806, 4806))

In [115]:
similarity= cosine_similarity(vectors)

In [117]:
similarity[0].shape

(4806,)

In [118]:
similarity[1]

array([0.06745406, 1.        , 0.07476672, ..., 0.02085144, 0.        ,
       0.02331262], shape=(4806,))

In [ ]:
def recommend(movie):
    movie_index= df[df['title'] == 'Batman Begins'].index[0]
    distances= similarity[movie_index]
    return

In [ ]:
df[df['title'] == 'Batman Begins'].index[0]

np.int64(119)

In [121]:
sorted(similarity[0], reverse=True)

[np.float64(1.0),
 np.float64(0.2714737592572808),
 np.float64(0.2362497692874473),
 np.float64(0.23489478196744007),
 np.float64(0.22874785549890703),
 np.float64(0.22758963106682426),
 np.float64(0.22264681319788207),
 np.float64(0.22264681319788207),
 np.float64(0.220112726581406),
 np.float64(0.20991342856239587),
 np.float64(0.20935201159410272),
 np.float64(0.20691022044226628),
 np.float64(0.20333142711013957),
 np.float64(0.20198929081169426),
 np.float64(0.20173664619648224),
 np.float64(0.1981014539232654),
 np.float64(0.19687480773953941),
 np.float64(0.19606959042763453),
 np.float64(0.19507682662870648),
 np.float64(0.19367337799588275),
 np.float64(0.18754844335438017),
 np.float64(0.18677184190940715),
 np.float64(0.1849316803638273),
 np.float64(0.1849316803638273),
 np.float64(0.18307302333807948),
 np.float64(0.18307302333807945),
 np.float64(0.1829982843991256),
 np.float64(0.18043874177926345),
 np.float64(0.18043874177926345),
 np.float64(0.17795362132005163),
 np.float64(0.17791499872137212),
 np.float64(0.1760901812651248),
 np.float64(0.17093520167692652),
 np.float64(0.17083256870359279),
 np.float64(0.17083256870359279),
 np.float64(0.17049858486761837),
 np.float64(0.17023607726794523),
 np.float64(0.17023607726794523),
 np.float64(0.1699096415365797),
 np.float64(0.16878498775964426),
 np.float64(0.16705381391691135),
 np.float64(0.16638958140993043),
 np.float64(0.16601941503058407),
 np.float64(0.1617491598051576),
 np.float64(0.160930171455096),
 np.float64(0.160930171455096),
 np.float64(0.1592795619605697),
 np.float64(0.1592795619605697),
 np.float64(0.1591320125431105),
 np.float64(0.15882898238187504),
 np.float64(0.15570941865504517),
 np.float64(0.15570941865504517),
 np.float64(0.15564320159117262),
 np.float64(0.1546617786679401),
 np.float64(0.15249857033260467),
 np.float64(0.15249857033260467),
 np.float64(0.15249857033260464),
 np.float64(0.15096588248481377),
 np.float64(0.15096588248481377),
 np.float64(0.15042366316917008),
 np.float64(0.1495371511386448),
 np.float64(0.1495371511386448),
 np.float64(0.1488671310552411),
 np.float64(0.14843120879858804),
 np.float64(0.14803422705323474),
 np.float64(0.14794534429106182),
 np.float64(0.1467418177209373),
 np.float64(0.14663102735578779),
 np.float64(0.1465158871516513),
 np.float64(0.14630761997152988),
 np.float64(0.14581652331529785),
 np.float64(0.14467284665112365),
 np.float64(0.14409760442605873),
 np.float64(0.14394032120171635),
 np.float64(0.1437770309379179),
 np.float64(0.1437770309379179),
 np.float64(0.1428976524688623),
 np.float64(0.14159136794714974),
 np.float64(0.1401683030060728),
 np.float64(0.13921151159742612),
 np.float64(0.13903059987499414),
 np.float64(0.1363988678940947),
 np.float64(0.1363988678940947),
 np.float64(0.13490812512398637),
 np.float64(0.13490812512398637),
 np.float64(0.13490812512398637),
 np.float64(0.13490812512398637),
 np.float64(0.13449109746432147),
 np.float64(0.13311166512794437),
 np.float64(0.13311166512794437),
 np.float64(0.1320676359488436),
 np.float64(0.1320676359488436),
 np.float64(0.13155474998819489),
 np.float64(0.1313989347611986),
 np.float64(0.13076644524148534),
 np.float64(0.13076644524148534),
 np.float64(0.1307130602850897),
 np.float64(0.1307130602850897),
 np.float64(0.13005121775247103),
 np.float64(0.130051217752471),
 np.float64(0.12939932784412608),
 np.float64(0.12888481555661677),
 np.float64(0.12888481555661674),
 np.float64(0.12888481555661674),
 np.float64(0.12888481555661674),
 np.float64(0.12812442652769462),
 np.float64(0.1281244265276946),
 np.float64(0.1281244265276946),
 np.float64(0.12719260014977868),
 np.float64(0.12719260014977868),
 np.float64(0.12719260014977868),
 np.float64(0.12535305264097507),
 np.float64(0.12535305264097507),
 np.float64(0.12535305264097507),
 np.float64(0.12535305264097507),
 np.float64(0.12494025332248496),
 np.float64(0.12494025332248496),
 np.float64(0.12451456127293808),
 np.float64(0.12451456127293808),
 np.float64(0.12451456127293806),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882337),
 np.float64(0.12369267399882337),
 np.float64(0.12337741817289974),
 np.float64(0.12337741817289974),
 np.float64(0.12227087189088334),
 np.float64(0.12227087189088334),
 np.float64(0.12209657262637608),
 np.float64(0.12209657262637608),
 np.float64(0.12209657262637608),
 np.float64(0.12209657262637608),
 np.float64(0.12199885626608374),
 np.float64(0.12199885626608374),
 np.float64(0.12056070554260304),
 np.float64(0.12056070554260302),
 np.float64(0.12056070554260302),
 np.float64(0.12014425971949098),
 np.float64(0.12014425971949098),
 np.float64(0.12014425971949098),
 np.float64(0.11962972091091584),
 np.float64(0.11962972091091584),
 np.float64(0.11912173678640628),
 np.float64(0.11908137705738524),
 np.float64(0.1186099991475814),
 np.float64(0.11765520133375293),
 np.float64(0.11765520133375293),
 np.float64(0.11739345417674985),
 np.float64(0.11715264683768396),
 np.float64(0.11627906976744186),
 np.float64(0.11527808354084698),
 np.float64(0.11527808354084698),
 np.float64(0.11527808354084698),
 np.float64(0.11527808354084698),
 np.float64(0.11495012246792571),
 np.float64(0.11437392774945351),
 np.float64(0.11437392774945351),
 np.float64(0.1143739277494535),
 np.float64(0.1143739277494535),
 np.float64(0.11366572324507891),
 np.float64(0.11366572324507891),
 np.float64(0.11366572324507891),
 np.float64(0.11349071817863016),
 np.float64(0.11349071817863016),
 np.float64(0.1132730943577198),
 np.float64(0.1132730943577198),
 np.float64(0.1132730943577198),
 np.float64(0.1132730943577198),
 np.float64(0.1132730943577198),
 np.float64(0.11242343760332196),
 np.float64(0.11242343760332196),
 np.float64(0.11242343760332196),
 np.float64(0.1113692092779409),
 np.float64(0.1113692092779409),
 np.float64(0.11122101332503227),
 np.float64(0.11122101332503227),
 np.float64(0.11122101332503227),
 np.float64(0.11095900821829636),
 np.float64(0.11095900821829636),
 np.float64(0.11015202290310472),
 np.float64(0.110056363290703),
 np.float64(0.10955820713295535),
 np.float64(0.10955820713295535),
 np.float64(0.10955820713295535),
 np.float64(0.10892755023757475),
 np.float64(0.10892755023757475),
 np.float64(0.10892755023757475),
 np.float64(0.10850463498834274),
 np.float64(0.10838718700289875),
 np.float64(0.10783277320343843),
 np.float64(0.10783277320343841),
 np.float64(0.10783277320343841),
 np.float64(0.10783277320343841),
 np.float64(0.10783277320343841),
 np.float64(0.10783277320343841),
 np.float64(0.10783277320343841),
 np.float64(0.10709164570498711),
 np.float64(0.1067703554397455),
 np.float64(0.10636559227784129),
 np.float64(0.10618637464037979),
 np.float64(0.10618637464037979),
 np.float64(0.10618637464037979),
 np.float64(0.10618637464037979),
 np.float64(0.10618637464037979),
 np.float64(0.10573873360945339),
 np.float64(0.10573873360945339),
 np.float64(0.10565410875907486),
 np.float64(0.10495671428119792),
 np.float64(0.10495671428119792),
 np.float64(0.10495671428119792),
 np.float64(0.104736448111277),
 np.float64(0.10473644811127698),
 np.float64(0.10473644811127698),
 np.float64(0.10473644811127697),
 np.float64(0.10461315619318828),
 np.float64(0.10376213439411505),
 np.float64(0.10376213439411505),
 np.float64(0.10360237735649558),
 np.float64(0.1031078524452934),
 np.float64(0.1031078524452934),
 np.float64(0.1031078524452934),
 np.float64(0.1031078524452934),
 np.float64(0.10271927240465611),
 np.float64(0.10229915092057101),
 np.float64(0.10229915092057101),
 np.float64(0.10229915092057101),
 np.float64(0.10189239324240279),
 np.float64(0.10189239324240279),
 np.float64(0.10189239324240279),
 np.float64(0.10189239324240279),
 np.float64(0.10189239324240279),
 np.float64(0.10166571355506977),
 np.float64(0.10166571355506977),
 np.float64(0.10166571355506977),
 np.float64(0.10166571355506977),
 np.float64(0.10166571355506977),
 np.float64(0.10166571355506977),
 np.float64(0.10166571355506977),
 np.float64(0.10166571355506977),
 np.float64(0.10166571355506977),
 np.float64(0.10166571355506977),
 np.float64(0.10166571355506977),
 np.float64(0.10166571355506977),
 np.float64(0.1010438990763711),
 np.float64(0.1010438990763711),
 np.float64(0.1010438990763711),
 np.float64(0.10099464540584711),
 np.float64(0.10042101125738147),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278005),
 np.float64(0.10028244211278003),
 np.float64(0.10012021643290915),
 np.float64(0.09983374884595828),
 np.float64(0.09983374884595828),
 np.float64(0.09983374884595828),
 np.float64(0.09983374884595828),
 np.float64(0.09954395505944927),
 np.float64(0.0992681139886719),
 np.float64(0.0992681139886719),
 np.float64(0.09926811398867189),
 np.float64(0.0989541391990587),
 np.float64(0.0989541391990587),
 np.float64(0.09843740386976972),
 np.float64(0.09843740386976971),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09767725810110087),
 np.float64(0.09762720569806997),
 np.float64(0.09762720569806997),
 np.float64(0.09762720569806997),
 np.float64(0.09762720569806997),
 np.float64(0.09753841331435326),
 np.float64(0.09753841331435326),
 np.float64(0.09753841331435326),
 np.float64(0.09753841331435326),
 np.float64(0.09753841331435326),
 np.float64(0.09753841331435326),
 np.float64(0.09683668899794137),
 np.float64(0.09683668899794137),
 np.float64(0.09683668899794137),
 np.float64(0.09644856443408242),
 np.float64(0.09644856443408242),
 np.float64(0.09644856443408242),
 np.float64(0.09606506961737248),
 np.float64(0.09606506961737248),
 np.float64(0.09539445011233401),
 np.float64(0.09539445011233401),
 np.float64(0.09539445011233401),
 np.float64(0.09539445011233401),
 np.float64(0.09531160645787792),
 np.float64(0.09531160645787792),
 np.float64(0.09531160645787792),
 np.float64(0.09531160645787792),
 np.float64(0.09531160645787792),
 np.float64(0.09526510164590819),
 np.float64(0.09526510164590819),
 np.float64(0.09526510164590819),
 np.float64(0.09526510164590819),
 np.float64(0.09526510164590819),
 np.float64(0.09412416106700235),
 np.float64(0.09412416106700235),
 np.float64(0.09412416106700235),
 np.float64(0.09412416106700235),
 np.float64(0.09412416106700235),
 np.float64(0.09338592095470356),
 np.float64(0.09338592095470356),
 np.float64(0.09315332801332622),
 np.float64(0.09302325581395349),
 np.float64(0.09302325581395349),
 np.float64(0.09302325581395349),
 np.float64(0.09302325581395349),
 np.float64(0.09302325581395349),
 np.float64(0.09302325581395349),
 np.float64(0.09302325581395349),
 np.float64(0.09302325581395349),
 np.float64(0.09302325581395349),
 np.float64(0.09302325581395349),
 np.float64(0.09302325581395349),
 np.float64(0.09302325581395349),
 np.float64(0.09246584018191364),
 np.float64(0.09196009797434057),
 np.float64(0.09196009797434057),
 np.float64(0.09196009797434057),
 np.float64(0.09196009797434057),
 np.float64(0.09196009797434057),
 np.float64(0.0914991421995628),
 np.float64(0.0914991421995628),
 np.float64(0.0914991421995628),
 np.float64(0.0914991421995628),
 np.float64(0.0914991421995628),
 np.float64(0.09113532707206115),
 np.float64(0.09093257859606313),
 np.float64(0.09093257859606313),
 np.float64(0.09093257859606313),
 np.float64(0.09093257859606313),
 np.float64(0.09093257859606313),
 np.float64(0.09093257859606313),
 np.float64(0.09093257859606313),
 np.float64(0.09049125308576025),
 np.float64(0.09049125308576025),
 np.float64(0.09049125308576025),
 np.float64(0.08993875008265757),
 np.float64(0.08993875008265757),
 np.float64(0.08993875008265757),
 np.float64(0.08993875008265757),
 np.float64(0.08993875008265757),
 np.float64(0.08993875008265757),
 np.float64(0.0898606443361987),
 np.float64(0.08972229068318688),
 np.float64(0.08972229068318688),
 np.float64(0.08972229068318688),
 np.float64(0.08972229068318688),
 np.float64(0.08972229068318688),
 np.float64(0.08972229068318688),
 np.float64(0.08972229068318688),
 np.float64(0.08972229068318688),
 np.float64(0.08924303808748926),
 np.float64(0.08897681066002582),
 np.float64(0.08897681066002582),
 np.float64(0.08897681066002582),
 np.float64(0.08897681066002582),
 np.float64(0.08897681066002582),
 np.float64(0.08897681066002582),
 np.float64(0.08897681066002582),
 np.float64(0.08863799356486773),
 np.float64(0.08863799356486773),
 np.float64(0.0880450906325624),
 np.float64(0.0880450906325624),
 np.float64(0.0880450906325624),
 np.float64(0.0880450906325624),
 np.float64(0.0880450906325624),
 np.float64(0.08804509063256238),
 np.float64(0.08804509063256238),
 np.float64(0.08804509063256238),
 np.float64(0.08804509063256238),
 np.float64(0.08804509063256238),
 np.float64(0.08804509063256238),
 np.float64(0.08804509063256238),
 np.float64(0.08804509063256238),
 np.float64(0.08804509063256238),
 np.float64(0.0871420401900598),
 np.float64(0.0871420401900598),
 np.float64(0.0871420401900598),
 np.float64(0.0871420401900598),
 np.float64(0.08689412492187135),
 np.float64(0.08645856265563523),
 np.float64(0.08645856265563523),
 np.float64(0.08645856265563523),
 np.float64(0.08645856265563523),
 np.float64(0.08645856265563523),
 np.float64(0.08645856265563523),
 np.float64(0.08645856265563523),
 np.float64(0.08645856265563523),
 np.float64(0.08645856265563523),
 np.float64(0.08633531446374632),
 np.float64(0.08633531446374632),
 np.float64(0.08626621856275073),
 np.float64(0.0854162843517964),
 np.float64(0.0854162843517964),
 np.float64(0.0854162843517964),
 np.float64(0.08524929243380919),
 np.float64(0.08495482076828985),
 np.float64(0.08495482076828985),
 np.float64(0.08495482076828985),
 np.float64(0.08495482076828985),
 np.float64(0.08495482076828985),
 np.float64(0.08495482076828985),
 np.float64(0.08472142796255815),
 np.float64(0.08472142796255815),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08459098688756271),
 np.float64(0.08378915848902159),
 np.float64(0.08369446361022048),
 np.float64(0.08352690695845567),
 np.float64(0.08352690695845567),
 np.float64(0.08352690695845567),
 np.float64(0.08352690695845567),
 np.float64(0.08352690695845567),
 np.float64(0.08352690695845567),
 np.float64(0.08352690695845567),
 np.float64(0.08352690695845567),
 np.float64(0.08352690695845567),
 np.float64(0.08310398319305214),
 np.float64(0.08300970751529205),
 np.float64(0.08300970751529205),
 np.float64(0.08300970751529205),
 np.float64(0.08300970751529205),
 np.float64(0.08300970751529205),
 np.float64(0.08300970751529205),
 np.float64(0.08300970751529205),
 np.float64(0.08300970751529205),
 np.float64(0.08270396169735617),
 np.float64(0.08225161211526649),
 np.float64(0.08225161211526649),
 np.float64(0.08225161211526649),
 np.float64(0.08216865534971651),
 np.float64(0.08216865534971651),
 np.float64(0.08216865534971651),
 np.float64(0.08216865534971651),
 np.float64(0.08216865534971651),
 np.float64(0.08151391459392224),
 np.float64(0.08151391459392224),
 np.float64(0.08151391459392224),
 np.float64(0.08151391459392224),
 np.float64(0.08151391459392224),
 np.float64(0.08151391459392224),
 np.float64(0.08151391459392224),
 np.float64(0.08151391459392224),
 np.float64(0.08151391459392224),
 np.float64(0.08151391459392224),
 np.float64(0.0808745799025788),
 np.float64(0.0808745799025788),
 np.float64(0.0808745799025788),
 np.float64(0.0808745799025788),
 np.float64(0.0808745799025788),
 np.float64(0.0808745799025788),
 np.float64(0.08079571632467769),
 np.float64(0.08079571632467769),
 np.float64(0.08079571632467769),
 np.float64(0.08079571632467769),
 np.float64(0.08079571632467769),
 np.float64(0.08079571632467769),
 np.float64(0.08079571632467769),
 np.float64(0.08009617314632732),
 np.float64(0.07993096945072023),
 np.float64(0.07963978098028485),
 np.float64(0.07963978098028485),
 np.float64(0.07963978098028485),
 np.float64(0.07963978098028485),
 np.float64(0.07963978098028485),
 np.float64(0.07963978098028485),
 np.float64(0.07941449119093752),
 np.float64(0.07941449119093752),
 np.float64(0.07941449119093752),
 np.float64(0.07941449119093752),
 np.float64(0.07874992309581577),
 np.float64(0.07874992309581577),
 np.float64(0.07874992309581577),
 np.float64(0.07874992309581577),
 np.float64(0.07874992309581577),
 np.float64(0.07874992309581577),
 np.float64(0.07874992309581577),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07845986714489121),
 np.float64(0.07823011594259385),
 np.float64(0.07810176455845598),
 np.float64(0.0774693511983531),
 np.float64(0.0774693511983531),
 np.float64(0.0774693511983531),
 np.float64(0.07741941928778483),
 np.float64(0.07741941928778483),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07733088933397005),
 np.float64(0.07685205569389798),
 np.float64(0.07685205569389798),
 np.float64(0.07685205569389798),
 np.float64(0.07685205569389798),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07624928516630233),
 np.float64(0.07587087446739768),
 np.float64(0.07566047878575344),
 np.float64(0.07566047878575344),
 np.float64(0.07521183158458504),
 np.float64(0.07521183158458504),
 np.float64(0.07521183158458504),
 np.float64(0.07521183158458504),
 np.float64(0.07521183158458504),
 np.float64(0.07521183158458504),
 np.float64(0.07521183158458504),
 np.float64(0.07521183158458504),
 np.float64(0.07521183158458504),
 np.float64(0.07521183158458504),
 np.float64(0.07521183158458504),
 np.float64(0.07521183158458504),
 np.float64(0.07508510557782777),
 np.float64(0.07508510557782777),
 np.float64(0.07508510557782777),
 np.float64(0.07508510557782777),
 np.float64(0.07452266241066098),
 np.float64(0.07452266241066098),
 np.float64(0.07421560439929402),
 np.float64(0.07421560439929402),
 np.float64(0.07421560439929402),
 np.float64(0.07421560439929402),
 np.float64(0.07421560439929402),

In [124]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(1214, np.float64(0.2714737592572808)),
 (582, np.float64(0.2362497692874473)),
 (2329, np.float64(0.23489478196744007)),
 (507, np.float64(0.22874785549890703)),
 (3728, np.float64(0.22758963106682426))]

In [ ]:
sorted(similarity[0], reverse=True)

[np.float64(1.0000000000000002),
 np.float64(0.7618767505376605),
 np.float64(0.7575273320432531),
 np.float64(0.7568668859029379),
 np.float64(0.7513064348758749),
 np.float64(0.7508592082683254),
 np.float64(0.7479761834565088),
 np.float64(0.7467922701568968),
 np.float64(0.7443042147509736),
 np.float64(0.7437419081653459)]

## Checking the Movies Similarities:

In [125]:
sorted(list(enumerate(similarity[0])), reverse= True, key=lambda x: x[1])[1: 6]

[(1214, np.float64(0.2714737592572808)),
 (582, np.float64(0.2362497692874473)),
 (2329, np.float64(0.23489478196744007)),
 (507, np.float64(0.22874785549890703)),
 (3728, np.float64(0.22758963106682426))]

In [129]:
def recommend(movie):
    movie_index= df[df['title'] == movie].index[0]
    distances= similarity[movie_index]
    movies_list= sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1: 6] 

    for i in movies_list:
        print(df.iloc[i[0]].title)

In [130]:
recommend('Avatar')

Aliens vs Predator: Requiem
Battle: Los Angeles
Predator
Independence Day
Falcon Rising

In [131]:
recommend('Batman Begins')

The Dark Knight
Batman
The Dark Knight Rises
Batman
Rockaway

In [132]:
df.iloc[1216].title

'Autumn in New York'